name: PR

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Check formatting
        run: mise run check-format
      - name: Lint
        run: mise run lint
      - name: Test
        run: mise run test
